//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCoreFunctional.UnionTypes.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DotNetCoreFunctional.UnionTypes.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NF0001Title {
            get {
                return ResourceManager.GetString("NF0001Title", resourceCulture);
            }
        }
        
        internal static string NF0001Description {
            get {
                return ResourceManager.GetString("NF0001Description", resourceCulture);
            }
        }
        
        internal static string NF0001MessageFormat {
            get {
                return ResourceManager.GetString("NF0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string NF0002Title {
            get {
                return ResourceManager.GetString("NF0002Title", resourceCulture);
            }
        }
        
        internal static string NF0002Description {
            get {
                return ResourceManager.GetString("NF0002Description", resourceCulture);
            }
        }
        
        internal static string NF0002MessageFormat {
            get {
                return ResourceManager.GetString("NF0002MessageFormat", resourceCulture);
            }
        }
        
        internal static string NF0002CodeFixTitle {
            get {
                return ResourceManager.GetString("NF0002CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string NF0003Title {
            get {
                return ResourceManager.GetString("NF0003Title", resourceCulture);
            }
        }
        
        internal static string NF0003Description {
            get {
                return ResourceManager.GetString("NF0003Description", resourceCulture);
            }
        }
        
        internal static string NF0003MessageFormat {
            get {
                return ResourceManager.GetString("NF0003MessageFormat", resourceCulture);
            }
        }
    }
}
