//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharperExtensions.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SharperExtensions.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SE0001Title {
            get {
                return ResourceManager.GetString("SE0001Title", resourceCulture);
            }
        }
        
        internal static string SE0001Description {
            get {
                return ResourceManager.GetString("SE0001Description", resourceCulture);
            }
        }
        
        internal static string SE0001MessageFormat {
            get {
                return ResourceManager.GetString("SE0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string SE0002Title {
            get {
                return ResourceManager.GetString("SE0002Title", resourceCulture);
            }
        }
        
        internal static string SE0002Description {
            get {
                return ResourceManager.GetString("SE0002Description", resourceCulture);
            }
        }
        
        internal static string SE0002MessageFormat {
            get {
                return ResourceManager.GetString("SE0002MessageFormat", resourceCulture);
            }
        }
        
        internal static string SE0002CodeFixTitle {
            get {
                return ResourceManager.GetString("SE0002CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string SE0003Title {
            get {
                return ResourceManager.GetString("SE0003Title", resourceCulture);
            }
        }
        
        internal static string SE0003Description {
            get {
                return ResourceManager.GetString("SE0003Description", resourceCulture);
            }
        }
        
        internal static string SE0003MessageFormat {
            get {
                return ResourceManager.GetString("SE0003MessageFormat", resourceCulture);
            }
        }
        
        internal static string SE0004Title {
            get {
                return ResourceManager.GetString("SE0004Title", resourceCulture);
            }
        }
        
        internal static string SE0004Description {
            get {
                return ResourceManager.GetString("SE0004Description", resourceCulture);
            }
        }
        
        internal static string SE0004MessageFormat {
            get {
                return ResourceManager.GetString("SE0004MessageFormat", resourceCulture);
            }
        }
        
        internal static string SE0005Title {
            get {
                return ResourceManager.GetString("SE0005Title", resourceCulture);
            }
        }
        
        internal static string SE0005Description {
            get {
                return ResourceManager.GetString("SE0005Description", resourceCulture);
            }
        }
        
        internal static string SE0005MessageFormat {
            get {
                return ResourceManager.GetString("SE0005MessageFormat", resourceCulture);
            }
        }
    }
}
